# Generated by Django 5.2.10 on 2026-01-07 22:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '1.6L Highline'", max_length=100)),
                ('year', models.IntegerField()),
                ('engine_cc', models.IntegerField(verbose_name='Engine CC')),
                ('horsepower', models.IntegerField(verbose_name='Horsepower')),
                ('fuel_consumption', models.FloatField(help_text='Liters/100km')),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
            ],
            options={
                'verbose_name': 'Car Trim',
                'verbose_name_plural': 'Car Trims',
                'ordering': ['-year', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Name (Arabic)')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Make',
                'verbose_name_plural': 'Makes',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_dealer', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('commercial_registry', models.ImageField(blank=True, upload_to='private/docs/')),
                ('tax_card', models.ImageField(blank=True, upload_to='private/docs/')),
                ('is_verified_dealer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (EGP)')),
                ('odometer', models.IntegerField(verbose_name='Odometer (km)')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(choices=[('CAIRO', 'Cairo'), ('ALEX', 'Alexandria'), ('GIZA', 'Giza'), ('QALIUBIYA', 'Qaliubiya'), ('SHARKIA', 'Sharkia'), ('DAKAHLIA', 'Dakahlia'), ('GHARBIA', 'Gharbia'), ('MENOUFIA', 'Menoufia'), ('BEHEIRA', 'Beheira'), ('KAFR_EL_SHEIKH', 'Kafr El Sheikh'), ('DAMIETTA', 'Damietta'), ('PORT_SAID', 'Port Said'), ('ISMAILIA', 'Ismailia'), ('SUEZ', 'Suez'), ('NORTH_SINAI', 'North Sinai'), ('SOUTH_SINAI', 'South Sinai'), ('RED_SEA', 'Red Sea'), ('FAIYUM', 'Faiyum'), ('BENI_SUEF', 'Beni Suef'), ('MINYA', 'Minya'), ('ASYUT', 'Asyut'), ('SOHAG', 'Sohag'), ('QENA', 'Qena'), ('LUXOR', 'Luxor'), ('ASWAN', 'Aswan'), ('NEW_VALLEY', 'New Valley'), ('MATROUH', 'Matrouh')], max_length=20, verbose_name='Location')),
                ('image_main', models.ImageField(upload_to='cars/%Y/%m/', verbose_name='Main Image')),
                ('image_2', models.ImageField(blank=True, upload_to='cars/%Y/%m/', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, upload_to='cars/%Y/%m/', verbose_name='Image 3')),
                ('image_4', models.ImageField(blank=True, upload_to='cars/%Y/%m/', verbose_name='Image 4')),
                ('image_5', models.ImageField(blank=True, upload_to='cars/%Y/%m/', verbose_name='Image 5')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_date', models.DateTimeField(blank=True, help_text='Set when admin approves', null=True)),
                ('views', models.IntegerField(default=0, verbose_name='View Count')),
                ('phone_clicks', models.IntegerField(default=0, verbose_name='Phone Reveal Clicks')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cartrim', verbose_name='Car Trim')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Name (Arabic)')),
                ('category', models.CharField(help_text='e.g., Sedan, SUV, Coupe', max_length=20)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.make')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['make', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='cartrim',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='core.model'),
        ),
    ]
