# Generated by Django 5.2.10 on 2026-01-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_description_ar_listing_description_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('CAIRO', 'Cairo'), ('ALEX', 'Alexandria'), ('GIZA', 'Giza'), ('SHARM', 'Sharm El Sheikh'), ('HURGHADA', 'Hurghada'), ('ALAMEIN', 'El Alamein'), ('DAHAB', 'Dahab'), ('MARSA_ALAM', 'Marsa Alam'), ('SIWA', 'Siwa Oasis'), ('QALIUBIYA', 'Qaliubiya'), ('SHARKIA', 'Sharkia'), ('DAKAHLIA', 'Dakahlia'), ('GHARBIA', 'Gharbia'), ('MENOUFIA', 'Menoufia'), ('BEHEIRA', 'Beheira'), ('KAFR_EL_SHEIKH', 'Kafr El Sheikh'), ('DAMIETTA', 'Damietta'), ('PORT_SAID', 'Port Said'), ('ISMAILIA', 'Ismailia'), ('SUEZ', 'Suez'), ('NORTH_SINAI', 'North Sinai'), ('SOUTH_SINAI', 'South Sinai'), ('RED_SEA', 'Red Sea'), ('FAIYUM', 'Faiyum'), ('BENI_SUEF', 'Beni Suef'), ('MINYA', 'Minya'), ('ASYUT', 'Asyut'), ('SOHAG', 'Sohag'), ('QENA', 'Qena'), ('LUXOR', 'Luxor'), ('ASWAN', 'Aswan'), ('NEW_VALLEY', 'New Valley'), ('MATROUH', 'Matrouh')], max_length=20, verbose_name='Location'),
        ),
    ]
